### ISSUE TITLE
[Feature Request] Add Dockerfile to allow creation of Docker Container Images

### ISSUE THREAD

**Issue by ZhunCn** [itsauric/karasu-music-bot#21]
Would love to host this on my unRAID server. I created a Dockerfile that works, but it depends on the .env file to be either there during the container creation or to have the file location set as a volume: `-v /mnt/user/appdata/karasu-discord-bot/.env:/karasu-discord-bot/src/.env`

Here is the Dockerfile that I'm currently using for this:
```
FROM node:alpine
WORKDIR karasu-music-bot
RUN apk add ffmpeg

COPY . .
RUN yarn install
RUN yarn build

CMD yarn karasu
```

I didn't get `bun` to work with Docker, so I just used node+yarn.

**Comment by itsauric** [comment]
I suggest you should look into Docker Compose if you haven't already. Another suggestion is passing the variables to the container as such: 

`docker run -e VAR1=value1 -e VAR2=value2 <image-name>`

I don't really know how Docker works, although I have tried it but maybe my suggestions could work.

**Comment by itsauric** [comment]
With Docker Compose, it should allow you to mount volumes and configure your container settings, so please do look into that.

**Comment by itsauric** [comment]
Issue closed due to inactivity
